#Sat Jun 06 22:26:07 IST 2026

android.injected.testOnly=false
kotlin.code.style=official
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -Dkotlin.daemon.jvm.options=-Xmx1536M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC
org.gradle.workers.max=4
org.gradle.daemon.idletimeout=600000
kotlin.daemon.client.alive.check.interval=300000
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=false
android.advanced.profiling.mode=NONE
android.experimental.runInSeparateProcess=false
