-dontobfuscate

-keep class com.google.googlejavaformat.** { *; }
-keep class org.eclipse.jdt.internal.core.util.** { *; }
-keep class com.sun.** { *; }
-keep class jdk.internal.** { *; }
-keep class org.osgi.** { *; }
-keep class javax.** { *; }
-keep class com.googlecode.** { *; }
-keep class org.jetbrains.kotlin.** { *; }
-keep class org.xml.sax.** { *; }
-keep class org.openjdk.com.sun.xml.internal.stream.** { *; }
