object Dependencies {
    const val CORE_LIBRARY_DESUGARING = "com.android.tools:desugar_jdk_libs:${BuildDependenciesVersions.CORE_LIBRARY_DESUGARING}"
    const val GUAVA = "com.google.guava:guava:${BuildDependenciesVersions.GUAVA}"
    const val APPCOMPAT = "androidx.appcompat:appcompat:${BuildDependenciesVersions.APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${BuildDependenciesVersions.MATERIAL}"
    const val LEAK_CANARY = "com.squareup.leakcanary:leakcanary-android:${BuildDependenciesVersions.LEAK_CANARY}"
    const val DEXLIB2 = "org.smali:dexlib2:${BuildDependenciesVersions.SMALI}"
    const val BAKSMALI = "org.smali:baksmali:${BuildDependenciesVersions.SMALI}"
    const val JAVAC = "io.github.itsaky:nb-javac-android:${BuildDependenciesVersions.JAVAC}"
    const val R8 = "com.android.tools:r8:${BuildDependenciesVersions.R8}"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${BuildDependenciesVersions.COROUTINES}"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:${BuildDependenciesVersions.RECYCLERVIEW}"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:${BuildDependenciesVersions.SWIPE_REFRESH_LAYOUT}"
    const val AUTO_VALUE = "com.google.auto.value:auto-value:${BuildDependenciesVersions.AUTO_VALUE}"
    const val AUTO_VALUE_ANNOTATIONS = "com.google.auto.value:auto-value-annotations:${BuildDependenciesVersions.AUTO_VALUE}"
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:${BuildDependenciesVersions.KOTLIN}"
    const val ANDROIDX_ANNOTATION = "androidx.annotation:annotation:${BuildDependenciesVersions.ANDROIDX_ANNOTATION}"
    const val TROVE4J = "org.jetbrains.intellij.deps:trove4j:${BuildDependenciesVersions.TROVE4J}"
    const val GSON = "com.google.code.gson:gson:${BuildDependenciesVersions.GSON}"
    const val JCODINGS = "org.jruby.jcodings:jcodings:${BuildDependenciesVersions.JCODINGS}"
    const val JONI = "org.jruby.joni:joni:${BuildDependenciesVersions.JONI}"
    const val FERNFLOWER = "com.github.Cosmic-Ide:fernflower:${BuildDependenciesVersions.FERNFLOWER}"
    const val PREFERENCE_KTX = "androidx.preference:preference-ktx:${BuildDependenciesVersions.PREFERENCE_KTX}"
    const val PREFERENCEX = "com.takisoft.preferencex:preferencex:${BuildDependenciesVersions.PREFERENCEX}"
    const val SIMPLEMENU_PREFERENCE = "dev.rikka.rikkax.preference:simplemenu-preference:${BuildDependenciesVersions.SIMPLEMENU_PREFERENCE}"
}