object Dependencies {
    const val CORE_LIBRARY_DESUGARING = "com.android.tools:desugar_jdk_libs:2.0.0"
    const val GUAVA = "com.google.guava:guava:31.1-jre"
    const val APPCOMPAT = "androidx.appcompat:appcompat:1.6.0-beta01"
    const val MATERIAL = "com.google.android.material:material:1.7.0-beta01"
    const val LEAK_CANARY = "com.squareup.leakcanary:leakcanary-android:2.9.1"
    const val DEXLIB2 = "org.smali:dexlib2:2.5.2"
    const val BAKSMALI = "org.smali:baksmali:2.5.2"
    const val JAVAC = "io.github.itsaky:nb-javac-android:17.0.0.4-SNAPSHOT"
    const val R8 = "com.android.tools:r8:3.3.75"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.3.0-beta02"
    const val SWIPE_REFRESH_LAYOUT = "androidx.swiperefreshlayout:swiperefreshlayout:1.2.0-alpha01"
    const val AUTO_VALUE = "com.google.auto.value:auto-value:1.9"
    const val AUTO_VALUE_ANNOTATIONS = "com.google.auto.value:auto-value-annotations:1.9"
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:1.7.20-RC"
    const val ANDROIDX_ANNOTATION = "androidx.annotation:annotation:1.5.0-beta01"
    const val TROVE4J = "org.jetbrains.intellij.deps:trove4j:1.0.20200330"
    const val GSON = "com.google.code.gson:gson:2.9.1"
    const val JCODINGS = "org.jruby.jcodings:jcodings:1.0.57"
    const val JONI = "org.jruby.joni:joni:2.1.43"
    const val FERNFLOWER = "com.github.Cosmic-Ide:fernflower:48c5d1a740"
    const val PREFERENCE_KTX = "androidx.preference:preference-ktx:1.2.0"
    const val PREFERENCEX = "com.takisoft.preferencex:preferencex:1.1.0"
    const val JDT_ANNOTATION = "org.eclipse.jdt:org.eclipse.jdt.annotation:2.2.600"
    const val SNAKEYAML = "org.yaml:snakeyaml:1.32"
}