name: Scan with Detekt

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '44 20 * * 3'
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.21.0

jobs:
  detekt:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup detekt
        id: detekt_setup
        uses: ./
        with:
          detekt_version: ${{ env.DETEKT_RELEASE_TAG }}


      - name: Show CLI tool contents
        run: |
          ls -la ${{ steps.detekt_setup.outputs.detekt }}

      - name: Run Detekt
        continue-on-error: true
        run: |
          detekt-cli --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/detekt.sarif.json
          checkout_path: ${{ github.workspace }}