name: Publish Snapshots

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Publish Snapshots to Maven
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: ./gradlew publishSnapshots --stacktrace
